FROM python:3.12-slim-bookworm

# Copy uv binaries directly into /bin
COPY --from=docker.io/astral/uv:latest /uv /uvx /bin/

WORKDIR /app

# Copy và cài đặt các thư viện cần thiết cho event service
COPY ../eventservice/requirements.txt .
RUN uv pip install --system --no-cache-dir -r requirements.txt

CMD ["sh", "-c", "watchfiles  --sigint-timeout 1 --sigkill-timeout 1 --filter python 'uvicorn src.main:app --host 0.0.0.0 --port 5001' /app"]