"""14 remove is_current from flow snapshot

Revision ID: 149d2c797d6f
Revises: 5da8926faf94
Create Date: 2025-09-20 15:22:20.630034

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "149d2c797d6f"
down_revision: Union[str, None] = "5da8926faf94"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("flow_snapshots", "is_current")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "flow_snapshots",
        sa.Column("is_current", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
