"""3 update base model schema

Revision ID: 1f980bf0ff17
Revises: 31851e277369
Create Date: 2025-07-23 17:38:35.981125

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1f980bf0ff17"
down_revision: Union[str, None] = "31851e277369"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "flow_executions", sa.Column("created_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "flow_executions", sa.Column("modified_at", sa.DateTime(), nullable=True)
    )
    op.drop_column("flow_executions", "time_modified")
    op.drop_column("flow_executions", "time_created")
    op.add_column("flows", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column("flows", sa.Column("modified_at", sa.DateTime(), nullable=True))
    op.drop_column("flows", "time_modified")
    op.drop_column("flows", "time_created")
    op.add_column("users", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column("users", sa.Column("modified_at", sa.DateTime(), nullable=True))
    op.drop_column("users", "time_modified")
    op.drop_column("users", "time_created")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "time_created", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "time_modified", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("users", "modified_at")
    op.drop_column("users", "created_at")
    op.add_column(
        "flows",
        sa.Column(
            "time_created", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "flows",
        sa.Column(
            "time_modified", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("flows", "modified_at")
    op.drop_column("flows", "created_at")
    op.add_column(
        "flow_executions",
        sa.Column(
            "time_created", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "flow_executions",
        sa.Column(
            "time_modified", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("flow_executions", "modified_at")
    op.drop_column("flow_executions", "created_at")
    # ### end Alembic commands ###
