"""13 add flow snapshot model

Revision ID: 23072a31d45e
Revises: 6358b6286ed1
Create Date: 2025-09-20 13:24:59.784046

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "23072a31d45e"
down_revision: Union[str, None] = "6358b6286ed1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "flow_snapshots",
        sa.Column("flow_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "flow_definition", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column(
            "snapshot_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("flow_schema_version", sa.String(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("modified_at", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["flow_id"], ["flows.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("flow_id", "version", name="uq_flow_snapshot_flow_version"),
    )
    op.create_index(
        "ix_flow_snapshots_flow_id", "flow_snapshots", ["flow_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_flow_snapshots_flow_id", table_name="flow_snapshots")
    op.drop_table("flow_snapshots")
    # ### end Alembic commands ###
