"""17 redesign test case and test run

Revision ID: 368fa6e36260
Revises: 68621235f406
Create Date: 2025-09-23 08:27:29.544501

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "368fa6e36260"
down_revision: Union[str, None] = "68621235f406"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "flow_test_case_runs",
        sa.Column("test_case_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "QUEUED",
                "RUNNING",
                "PASSED",
                "FAILED",
                "CANCELLED",
                "SYSTEM_ERROR",
                name="test_case_run_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "actual_output", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("execution_time_ms", sa.Float(), nullable=True),
        sa.Column("run_detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "criteria_results", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("trigger_type", sa.String(), nullable=True),
        sa.Column("triggered_by", sa.String(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("modified_at", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["test_case_id"], ["flow_test_cases.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "flow_test_cases",
        sa.Column(
            "flow_definition", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
    )
    op.add_column(
        "flow_test_cases",
        sa.Column(
            "input_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.drop_column("flow_test_cases", "run_detail")
    op.drop_column("flow_test_cases", "execution_time_ms")
    op.drop_column("flow_test_cases", "error_message")
    op.drop_column("flow_test_cases", "status")
    op.drop_column("flow_test_cases", "test_metadata")
    op.drop_column("flow_test_cases", "actual_output")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "flow_test_cases",
        sa.Column(
            "actual_output",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "flow_test_cases",
        sa.Column(
            "test_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "flow_test_cases",
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING",
                "QUEUED",
                "RUNNING",
                "PASSED",
                "FAILED",
                "CANCEL",
                name="test_case_status",
            ),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "flow_test_cases",
        sa.Column("error_message", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "flow_test_cases",
        sa.Column(
            "execution_time_ms",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "flow_test_cases",
        sa.Column(
            "run_detail",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("flow_test_cases", "input_metadata")
    op.drop_column("flow_test_cases", "flow_definition")
    op.drop_table("flow_test_case_runs")
    # ### end Alembic commands ###
