"""16 changed expected output to pass criteria

Revision ID: 38f48620411e
Revises: 622441796c34
Create Date: 2025-09-22 10:46:31.384623

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "38f48620411e"
down_revision: Union[str, None] = "622441796c34"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "flow_test_cases",
        sa.Column(
            "pass_criteria", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.drop_column("flow_test_cases", "expected_output")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "flow_test_cases",
        sa.Column(
            "expected_output",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("flow_test_cases", "pass_criteria")
    # ### end Alembic commands ###
