"""17 redesign for test case and test runs

Revision ID: 5a0dbe74391f
Revises: 68621235f406
Create Date: 2025-09-23 08:06:37.329394

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5a0dbe74391f"
down_revision: Union[str, None] = "68621235f406"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "flow_test_cases",
        sa.Column(
            "flow_definition", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
    )
    op.add_column(
        "flow_test_cases",
        sa.Column(
            "input_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.drop_column("flow_test_cases", "run_detail")
    op.drop_column("flow_test_cases", "status")
    op.drop_column("flow_test_cases", "test_metadata")
    op.drop_column("flow_test_cases", "actual_output")
    op.drop_column("flow_test_cases", "execution_time_ms")
    op.drop_column("flow_test_cases", "error_message")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "flow_test_cases",
        sa.Column("error_message", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "flow_test_cases",
        sa.Column(
            "execution_time_ms",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "flow_test_cases",
        sa.Column(
            "actual_output",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "flow_test_cases",
        sa.Column(
            "test_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "flow_test_cases",
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING",
                "QUEUED",
                "RUNNING",
                "PASSED",
                "FAILED",
                "CANCEL",
                name="test_case_status",
            ),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "flow_test_cases",
        sa.Column(
            "run_detail",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("flow_test_cases", "input_metadata")
    op.drop_column("flow_test_cases", "flow_definition")
    # ### end Alembic commands ###
