"""13 add flow snapshot

Revision ID: 5da8926faf94
Revises: 6358b6286ed1
Create Date: 2025-09-20 15:05:17.452797

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5da8926faf94"
down_revision: Union[str, None] = "6358b6286ed1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "flow_snapshots",
        sa.Column("flow_id", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "flow_definition", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column(
            "snapshot_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("flow_schema_version", sa.String(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("modified_at", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["flow_id"], ["flows.flow_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("flow_snapshots")
    # ### end Alembic commands ###
