"""11 add is_playground for session

Revision ID: 5e719a7abc59
Revises: fcf6be1f04d6
Create Date: 2025-09-16 15:53:41.806078

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5e719a7abc59"
down_revision: Union[str, None] = "fcf6be1f04d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sessions", sa.Column("is_playground", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sessions", "is_playground")
    # ### end Alembic commands ###
