"""22 fix simple_suite_id to simple_id

Revision ID: 601e3917a875
Revises: 80cae42afdc3
Create Date: 2025-09-27 13:19:37.254194

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "601e3917a875"
down_revision: Union[str, None] = "80cae42afdc3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "flow_test_suites", sa.Column("simple_id", sa.String(), nullable=True)
    )
    op.drop_column("flow_test_suites", "simple_suite_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "flow_test_suites",
        sa.Column("simple_suite_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("flow_test_suites", "simple_id")
    # ### end Alembic commands ###
