"""12 link session with flow

Revision ID: 6358b6286ed1
Revises: 5e719a7abc59
Create Date: 2025-09-16 16:01:22.727121

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6358b6286ed1"
down_revision: Union[str, None] = "5e719a7abc59"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None, "sessions", "flows", ["flow_id"], ["flow_id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "sessions", type_="foreignkey")
    # ### end Alembic commands ###
