"""21 add fastnano id generation for simple id of test suite and test case

Revision ID: 80cae42afdc3
Revises: c277b09ddd66
Create Date: 2025-09-27 13:10:15.539166

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "80cae42afdc3"
down_revision: Union[str, None] = "c277b09ddd66"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("flow_test_cases", sa.Column("simple_id", sa.String(), nullable=True))
    op.add_column(
        "flow_test_suites", sa.Column("simple_suite_id", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("flow_test_suites", "simple_suite_id")
    op.drop_column("flow_test_cases", "simple_id")
    # ### end Alembic commands ###
