"""6. Update ApiKey schema

Revision ID: a9a78519a564
Revises: a110df9b2123
Create Date: 2025-08-20 15:39:38.854127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9a78519a564'
down_revision: Union[str, None] = 'a110df9b2123'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('key_id', sa.String(length=255), nullable=False))
    op.alter_column('api_keys', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_unique_constraint(None, 'api_keys', ['key_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'api_keys', type_='unique')
    op.alter_column('api_keys', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('api_keys', 'key_id')
    # ### end Alembic commands ###
