"""8 add session and message history

Revision ID: bfa4fe0a9d70
Revises: 5093242646d6
Create Date: 2025-09-16 08:33:26.333663

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bfa4fe0a9d70"
down_revision: Union[str, None] = "5093242646d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sessions",
        sa.Column("flow_id", sa.String(length=64), nullable=True),
        sa.Column(
            "session_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("modified_at", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_sessions_flow_id", "sessions", ["flow_id"], unique=False)
    op.create_index(op.f("ix_sessions_flow_id"), "sessions", ["flow_id"], unique=False)
    op.create_table(
        "sessions_chat_histories",
        sa.Column("session_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "role", sa.Enum("user", "assistant", name="sender_type"), nullable=False
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "chat_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("modified_at", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_chat_histories_role", "sessions_chat_histories", ["role"], unique=False
    )
    op.create_index(
        "idx_chat_histories_session_id",
        "sessions_chat_histories",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sessions_chat_histories_role"),
        "sessions_chat_histories",
        ["role"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sessions_chat_histories_session_id"),
        "sessions_chat_histories",
        ["session_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_sessions_chat_histories_session_id"),
        table_name="sessions_chat_histories",
    )
    op.drop_index(
        op.f("ix_sessions_chat_histories_role"), table_name="sessions_chat_histories"
    )
    op.drop_index("idx_chat_histories_session_id", table_name="sessions_chat_histories")
    op.drop_index("idx_chat_histories_role", table_name="sessions_chat_histories")
    op.drop_table("sessions_chat_histories")
    op.drop_index(op.f("ix_sessions_flow_id"), table_name="sessions")
    op.drop_index("idx_sessions_flow_id", table_name="sessions")
    op.drop_table("sessions")
    # ### end Alembic commands ###
