"""20 add new fields for test case run for tracking in celery task

Revision ID: c277b09ddd66
Revises: ccc8f0f4d577
Create Date: 2025-09-25 17:47:12.038980

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c277b09ddd66"
down_revision: Union[str, None] = "ccc8f0f4d577"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "flow_test_case_runs", sa.Column("task_run_id", sa.String(), nullable=True)
    )
    op.add_column(
        "flow_test_case_runs", sa.Column("started_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "flow_test_case_runs", sa.Column("finished_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("flow_test_case_runs", "finished_at")
    op.drop_column("flow_test_case_runs", "started_at")
    op.drop_column("flow_test_case_runs", "task_run_id")
    # ### end Alembic commands ###
