"""19 update input_data to input_text in flow-test-model

Revision ID: ccc8f0f4d577
Revises: 11755162253d
Create Date: 2025-09-23 17:24:41.050190

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ccc8f0f4d577"
down_revision: Union[str, None] = "11755162253d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("flow_test_cases", sa.Column("input_text", sa.Text(), nullable=True))
    op.drop_column("flow_test_cases", "input_data")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "flow_test_cases",
        sa.Column(
            "input_data",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("flow_test_cases", "input_text")
    # ### end Alembic commands ###
