"""9 add user_defined_session_id to session model

Revision ID: ced759984ca2
Revises: bfa4fe0a9d70
Create Date: 2025-09-16 08:52:20.687883

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ced759984ca2"
down_revision: Union[str, None] = "bfa4fe0a9d70"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sessions", sa.Column("user_defined_session_id", sa.String(), nullable=True)
    )
    op.create_index(
        "idx_sessions_user_defined_session_id",
        "sessions",
        ["user_defined_session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sessions_user_defined_session_id"),
        "sessions",
        ["user_defined_session_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sessions_user_defined_session_id"), table_name="sessions")
    op.drop_index("idx_sessions_user_defined_session_id", table_name="sessions")
    op.drop_column("sessions", "user_defined_session_id")
    # ### end Alembic commands ###
