"""4 add flow and user relation

Revision ID: f8331f5de31a
Revises: 1f980bf0ff17
Create Date: 2025-07-24 15:55:25.232662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8331f5de31a'
down_revision: Union[str, None] = '1f980bf0ff17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flows', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'flows', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flows', type_='foreignkey')
    op.drop_column('flows', 'user_id')
    # ### end Alembic commands ###
